[tool.poetry]
name = "graful-sys-mon"
version = "0.1.0"
description = ""
authors = ["0xAungkon <only.coder000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
